packages:
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild
minimumReleaseAge: 1440 # 1 day
minimumReleaseAgeExclude:
  - '@rollup/*'
verifyDepsBeforeRun: install
trustPolicy: no-downgrade
trustPolicyExclude:
  - 'chokidar@4.0.3'
  - undici@5.29.0
