packages:
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild
minimumReleaseAge: 1440 # 1 day
minimumReleaseAgeExclude:
  - "chokidar@4.0.3"
  - '@rollup/*'
verifyDepsBeforeRun: install
trustPolicy: no-downgrade
