packages:
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild
minimumReleaseAge: 1440 # 1 day
minimumReleaseAgeExclude:
  - '@rollup/*'
  - better-auth@1.4.8-beta.1
  - '@better-auth/*'
verifyDepsBeforeRun: install
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - undici@5.29.0
  - langium@3.3.1
